name: Release - Staging
on:
  push:
    branches:
      - master

env:
  S3_BUCKET: platform-staging.vas.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Deps
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}

      - name: Build
        run: yarn run react-scripts --max_old_space_size=4096 build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
          REACT_APP_API_HOST: https://platform-api-staging.vas.com/api/
          NODE_ENV: production
          REACT_APP_ENV: staging
          REACT_APP_ENABLE_DEV_TOOLS: false
          REACT_APP_GOLDBERG_INTEGRATION_ID: 17
          REACT_APP_MEDICINES_MS_URL: https://staging.integration-vas.com/medicine/
          REACT_APP_AGGREGATORS_MS_URL: https://staging.integration-vas.com/aggregators/

      - name: Deploy
        run: |
          aws s3 sync build s3://${{ env.S3_BUCKET }} --delete --region us-east-1 --acl public-read --cache-control 'max-age=2419200, must-revalidate, public'
          aws s3 cp s3://${{ env.S3_BUCKET }}/apple-icon-152x152.png s3://${{ env.S3_BUCKET }}/apple-icon-152x152.png --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
          aws s3 cp s3://${{ env.S3_BUCKET }}/asset-manifest.json s3://${{ env.S3_BUCKET }}/asset-manifest.json --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
          aws s3 cp s3://${{ env.S3_BUCKET }}/favicon.ico s3://${{ env.S3_BUCKET }}/favicon.ico --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
          aws s3 cp s3://${{ env.S3_BUCKET }}/index.html s3://${{ env.S3_BUCKET }}/index.html --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
          aws s3 cp s3://${{ env.S3_BUCKET }}/manifest.json s3://${{ env.S3_BUCKET }}/manifest.json --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
          aws s3 cp s3://${{ env.S3_BUCKET }}/service-worker.js s3://${{ env.S3_BUCKET }}/service-worker.js --region us-east-1 --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Start E2E Tests
        if: success()
        env:
          VAS_BUILD_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
        run: |
          curl -d "{\"event_type\": \"test-on-demand\", \"client_payload\": { \"github_sha\": \"$GITHUB_SHA\", \"github_ref\": \"$GITHUB_REF\", \"github_repository\": \"$GITHUB_REPOSITORY\", \"github_actor\": \"$GITHUB_ACTOR\"} }" -H "Content-Type: application/json" -H "Authorization: token ${VAS_BUILD_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/vas-dev/Morpheus-E2E/dispatches"
