name: Update @vas-dev/vas-ui

on:
  repository_dispatch:
    types: [vas-fe-published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Deps
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}

      - name: Update vas-fe
        uses: ./.github/actions/update-vas-fe
        env:
          GITHUB_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
        with:
          actor: ${{ github.event.client_payload.actor }}
      - run: echo ${{ github.event.client_payload.actor }}
