name: Update @vas-dev/vas-ui

on:
  repository_dispatch:
    types: [vas-fe-published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update vas-fe
        uses: ./.github/actions/update-vas-fe
        #env:
          #GITHUB_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
          #NODE_AUTH_TOKEN: ${{ secrets.VAS_BUILD_TOKEN }}
        with:
          actor: ${{ github.event.client_payload }}